// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pigrrcperaohkoroomkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZ3JyY3BlcmFvaGtvcm9vbWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjEzMjIsImV4cCI6MjA2OTI5NzMyMn0.7UATlu-r-vYj0xTmwIHcdNMoJ5207UYAL3Sa13RvUXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});